package com.qdw.feishu.infrastructure.gateway;

import com.qdw.feishu.domain.exception.OptimisticLockException;
import com.qdw.feishu.domain.session.AppSession;
import com.qdw.feishu.domain.session.AppSessionInfo;
import com.qdw.feishu.domain.session.SessionIdGenerator;
import com.qdw.feishu.domain.session.SessionState;
import com.qdw.feishu.domain.session.TypeToken;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.io.TempDir;

import java.nio.file.Path;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.concurrent.atomic.AtomicLong;

import static org.junit.jupiter.api.Assertions.*;

/**
 * AppSessionGatewayImpl 测试 (Phase 2 - 独立 SQLite 存储)
 * 
 * 验证乐观锁机制和状态转换的正确性
 */
class AppSessionGatewayImplTest {

    private static final String DB_PATH = "test-app-session.db";
    private static final String APP_ID = "test-app";
    private static final String SESSION_ID = "ses_abc123";
    
    private AppSessionGatewayImpl gateway;
    private SessionIdGenerator sessionIdGenerator;
    
    @TempDir
    Path tempDir;
    
    private final AtomicLong idCounter = new AtomicLong(0);
    
    @BeforeEach
    void setUp() {
        // Create simple ID generator
        sessionIdGenerator = appId -> "ses_" + idCounter.incrementAndGet() + "_" + System.currentTimeMillis();
        
        String dbPath = tempDir.resolve(DB_PATH).toString();
        javax.sql.DataSource testDataSource = org.springframework.boot.jdbc.DataSourceBuilder.create()
                .url("jdbc:sqlite:" + dbPath)
                .driverClassName("org.sqlite.JDBC")
                .build();
        gateway = new AppSessionGatewayImpl(sessionIdGenerator, testDataSource, dbPath);
        gateway.init();
    }
    
    @AfterEach
    void tearDown() {
        gateway.cleanup();
    }

    // ========== 会话创建测试 ==========

    @Test
    void should_createSession_withAutoGeneratedId() {
        Map<String, String> data = Map.of("key", "value");
        String sessionId = gateway.createSession(APP_ID, data, new TypeToken<Map<String, String>>() {});
        
        assertNotNull(sessionId);
        assertTrue(sessionId.startsWith("ses_"));
    }

    @Test
    void should_createSession_withCustomId() {
        Map<String, String> data = Map.of("key", "value");
        String customId = "custom_session_id";
        
        String sessionId = gateway.createSession(APP_ID, customId, data, new TypeToken<Map<String, String>>() {});
        
        assertEquals(customId, sessionId);
    }

    // ========== 会话查询测试 ==========

    @Test
    void should_getSession_returnSession_whenExists() {
        Map<String, String> data = Map.of("key", "value");
        String sessionId = gateway.createSession(APP_ID, data, new TypeToken<Map<String, String>>() {});
        
        Optional<AppSession<Map<String, String>>> result = 
            gateway.getSession(APP_ID, sessionId, new TypeToken<Map<String, String>>() {});
        
        assertTrue(result.isPresent());
        assertEquals(sessionId, result.get().getSessionId());
        assertEquals(APP_ID, result.get().getAppId());
        assertEquals(data, result.get().getData());
    }

    @Test
    void should_getSession_returnEmpty_whenNotExists() {
        Optional<AppSession<Map<String, String>>> result = 
            gateway.getSession(APP_ID, "nonexistent", new TypeToken<Map<String, String>>() {});
        
        assertTrue(result.isEmpty());
    }

    @Test
    void should_listSessions_returnAllSessions() {
        Map<String, String> data1 = Map.of("key", "value1");
        Map<String, String> data2 = Map.of("key", "value2");
        
        gateway.createSession(APP_ID, data1, new TypeToken<Map<String, String>>() {});
        gateway.createSession(APP_ID, data2, new TypeToken<Map<String, String>>() {});
        
        List<AppSessionInfo> sessions = gateway.listSessions(APP_ID);
        
        assertEquals(2, sessions.size());
    }

    @Test
    void should_countActiveSessions_returnCorrectCount() {
        Map<String, String> data1 = Map.of("key", "value1");
        Map<String, String> data2 = Map.of("key", "value2");
        
        String ses1 = gateway.createSession(APP_ID, data1, new TypeToken<Map<String, String>>() {});
        String ses2 = gateway.createSession(APP_ID, data2, new TypeToken<Map<String, String>>() {});
        
        // 激活会话
        gateway.activateSession(APP_ID, ses1);
        gateway.activateSession(APP_ID, ses2);
        
        int count = gateway.countActiveSessions(APP_ID);
        
        assertEquals(2, count);
    }

    // ========== 乐观锁测试 ==========

    @Test
    void should_throwOptimisticLockException_when_concurrentUpdate() {
        Map<String, String> data = Map.of("key", "v1");
        String sessionId = gateway.createSession(APP_ID, data, new TypeToken<Map<String, String>>() {});
        
        // 用错误的 version 更新
        assertThrows(OptimisticLockException.class, () ->
            gateway.updateSession(APP_ID, sessionId, 
                Map.of("key", "v2"), 
                new TypeToken<Map<String, String>>() {}, 
                999L  // 错误的 version
            )
        );
    }

    @Test
    void should_allowSequentialUpdates_when_versionMatches() {
        Map<String, String> data = Map.of("key", "v1");
        String sessionId = gateway.createSession(APP_ID, data, new TypeToken<Map<String, String>>() {});
        
        // 第一次更新（version 1 -> 2）
        assertDoesNotThrow(() -> 
            gateway.updateSession(APP_ID, sessionId, 
                Map.of("key", "v2"), new TypeToken<Map<String, String>>() {}, 1L)
        );
        
        // 第二次更新（version 2 -> 3）
        assertDoesNotThrow(() -> 
            gateway.updateSession(APP_ID, sessionId, 
                Map.of("key", "v3"), new TypeToken<Map<String, String>>() {}, 2L)
        );
    }

    @Test
    void should_throwOptimisticLockException_when_updateStateWithWrongVersion() {
        Map<String, String> data = Map.of("key", "test");
        String sessionId = gateway.createSession(APP_ID, data, new TypeToken<Map<String, String>>() {});
        
        // 激活会话使 version 变为 2
        gateway.activateSession(APP_ID, sessionId);
        
        // 用错误的 version=1 更新状态
        assertThrows(OptimisticLockException.class, () ->
            gateway.updateState(APP_ID, sessionId, SessionState.IDLE, 1L)
        );
    }

    // ========== 状态转换测试 ==========

    @Test
    void should_allowValidStateTransition_when_createdToActive() {
        Map<String, String> data = Map.of("key", "test");
        String sessionId = gateway.createSession(APP_ID, data, new TypeToken<Map<String, String>>() {});
        
        // CREATED -> ACTIVE 应该成功
        assertDoesNotThrow(() -> 
            gateway.activateSession(APP_ID, sessionId)
        );
        
        Optional<AppSession<Map<String, String>>> result = 
            gateway.getSession(APP_ID, sessionId, new TypeToken<Map<String, String>>() {});
        assertTrue(result.isPresent());
        assertEquals(SessionState.ACTIVE, result.get().getState());
    }

    @Test
    void should_allowValidStateTransition_when_activeToIdle() {
        Map<String, String> data = Map.of("key", "test");
        String sessionId = gateway.createSession(APP_ID, data, new TypeToken<Map<String, String>>() {});
        
        gateway.activateSession(APP_ID, sessionId);
        
        // ACTIVE -> IDLE 应该成功
        assertDoesNotThrow(() -> 
            gateway.idleSession(APP_ID, sessionId)
        );
        
        Optional<AppSession<Map<String, String>>> result = 
            gateway.getSession(APP_ID, sessionId, new TypeToken<Map<String, String>>() {});
        assertTrue(result.isPresent());
        assertEquals(SessionState.IDLE, result.get().getState());
    }

    @Test
    void should_allowValidStateTransition_when_idleToActive() {
        Map<String, String> data = Map.of("key", "test");
        String sessionId = gateway.createSession(APP_ID, data, new TypeToken<Map<String, String>>() {});
        
        gateway.activateSession(APP_ID, sessionId);
        gateway.idleSession(APP_ID, sessionId);
        
        // IDLE -> ACTIVE 应该成功
        assertDoesNotThrow(() -> 
            gateway.activateSession(APP_ID, sessionId)
        );
        
        Optional<AppSession<Map<String, String>>> result = 
            gateway.getSession(APP_ID, sessionId, new TypeToken<Map<String, String>>() {});
        assertTrue(result.isPresent());
        assertEquals(SessionState.ACTIVE, result.get().getState());
    }

    @Test
    void should_allowValidStateTransition_when_activeToTerminated() {
        Map<String, String> data = Map.of("key", "test");
        String sessionId = gateway.createSession(APP_ID, data, new TypeToken<Map<String, String>>() {});
        
        gateway.activateSession(APP_ID, sessionId);
        
        // ACTIVE -> TERMINATED 应该成功
        assertDoesNotThrow(() -> 
            gateway.terminateSession(APP_ID, sessionId)
        );
    }

    @Test
    void should_throwIllegalStateException_when_terminatedToActive() {
        Map<String, String> data = Map.of("key", "test");
        String sessionId = gateway.createSession(APP_ID, data, new TypeToken<Map<String, String>>() {});
        
        gateway.activateSession(APP_ID, sessionId);
        gateway.terminateSession(APP_ID, sessionId);
        
        // TERMINATED -> ACTIVE 应该失败
        assertThrows(IllegalStateException.class, () ->
            gateway.updateState(APP_ID, sessionId, SessionState.ACTIVE, 3L)
        );
    }

    @Test
    void should_throwIllegalStateException_when_terminatedToIdle() {
        Map<String, String> data = Map.of("key", "test");
        String sessionId = gateway.createSession(APP_ID, data, new TypeToken<Map<String, String>>() {});
        
        gateway.activateSession(APP_ID, sessionId);
        gateway.terminateSession(APP_ID, sessionId);
        
        // TERMINATED -> IDLE 应该失败
        assertThrows(IllegalStateException.class, () ->
            gateway.updateState(APP_ID, sessionId, SessionState.IDLE, 3L)
        );
    }

    // ========== 会话删除测试 ==========

    @Test
    void should_deleteSession_removeFromStorage() {
        Map<String, String> data = Map.of("key", "test");
        String sessionId = gateway.createSession(APP_ID, data, new TypeToken<Map<String, String>>() {});
        
        gateway.deleteSession(APP_ID, sessionId);
        
        Optional<AppSession<Map<String, String>>> result = 
            gateway.getSession(APP_ID, sessionId, new TypeToken<Map<String, String>>() {});
        assertTrue(result.isEmpty());
    }

    @Test
    void should_cleanupSessions_removeTerminatedAndExpired() {
        Map<String, String> data = Map.of("key", "test");
        String sessionId1 = gateway.createSession(APP_ID, "ses_1", data, new TypeToken<Map<String, String>>() {});
        String sessionId2 = gateway.createSession(APP_ID, "ses_2", data, new TypeToken<Map<String, String>>() {});
        
        // 终止一个会话
        gateway.activateSession(APP_ID, sessionId1);
        gateway.terminateSession(APP_ID, sessionId1);
        
        // 清理
        int removed = gateway.cleanupSessions(APP_ID);
        
        assertEquals(1, removed);
        
        // 验证只有 ses_2 剩余
        List<AppSessionInfo> sessions = gateway.listSessions(APP_ID);
        assertEquals(1, sessions.size());
        assertEquals("ses_2", sessions.get(0).getSessionId());
    }
}
